// This file was automatically generated by Beschi v0.3.2
// <https://github.com/sjml/beschi>
// Do not edit directly.

/*
DATA PROTOCOL
-----------------
[meta]
namespace = "WasmBots"
list_size_type = "uint16"
string_size_type = "byte"

# used internally for handling host <-> module mishaps
[[messages]]
_name = "_Error"
description = "string"

[[enums]]
_name = "GameMode"
_values = [
	"Wander", # the proof-of-concept "navigate with no stakes" mode
	"Attain", # find the amulet
]

# initial setup message that you can either accept or reject
[[messages]]
_name = "InitialParameters"
paramsVersion = "uint16"       # version of this very message, so you know if you can parse the rest
engineVersionMajor = "uint16"  # major version of engine
engineVersionMinor = "uint16"  # minor version of engine
engineVersionPatch = "uint16"  # patch version of engine
diagonalMovement = "bool"      # if false, any attempted diagonal move will be Invalid
playerStride = "byte"          # how far you can move on a given turn
playerOpenReach = "byte"       # the distance at which you can open things (doors, chests)
gameMode = "GameMode"          # what type of game we're going to play

[[structs]]
_name = "Point"
x = "int16"
y = "int16"


[[enums]]
_name = "MoveResult"
_values = [
	"Succeeded",  # your move worked (ex: attack hit, moved successfully)
	"Failed",     # your move did not work (ex: attack missed, moved into wall)
	"Invalid",    # your move was not allowed by the system (ex: tried diagonal movement when not allowed, targeted something out of range)
	"Error",      # your move was not understood (ex: malformed message, missing data)
]

[[enums]]
_name = "TileType"
_values = [
	"Void",        # you don't know what's there; might be off the edge of the map, or maybe just behind a wall
	"Floor",       # an open space you can move to
	"OpenDoor",    # a door space that you can pass through or take a turn to target with Close
	"ClosedDoor",  # an impassable door space that you can take a turn to target with Open
	"Wall",        # an impassable space
]

[[enums]]
_name = "Direction"
_values = [
	"North",
	"Northeast",
	"East",
	"Southeast",
	"South",
	"Southwest",
	"West",
	"Northwest",
]

[[enums]]
_name = "EntityType"
_values = [
	"Player",
	"Item",
]

[[structs]]
_name = "Entity"
id = "uint32"
entityType = "EntityType"
surroundingsIndex = "uint16"
label = "string"
dataByteA = "byte"
dataByteB = "byte"
dataIntA = "int32"
dataIntB = "int32"

[[enums]]
_name = "ItemType"
_values = [
	"Stone",
	"Amulet",
]

# player receives every tick
[[messages]]
_name = "PresentCircumstances"  # describes your immediate situation and surroundings at the start of this turn
lastTickDuration = "uint32"     # how long, in milliseconds, you took on the last tick (will be 0 on initial turn)
lastMoveResult = "MoveResult"   # the result of your last turn (will be Succeeded on initial turn)
currentHitPoints = "uint16"     # how many hit points you have
surroundings = "[TileType]"     # array of tiles representing your immediate surroundings as a square with you in the middle
surroundingsRadius = "byte"     # radius (from you) of the surroundings, so the side of a square is (this * 2) + 1
visibleEntities = "[Entity]"    # array of entities within your current field of view

### moves that the player submits

[[messages]]
_name = "Wait"  # no-op; don't do anything and wait for the next tick

[[messages]]
_name = "Resign"  # give up the game; you will receive no more tick calls after submitting this move

[[messages]]
_name = "MoveTo"         # move to a new tile
direction = "Direction"  # which way to move
distance = "byte"        # how far to move (can usually just be 1, but might be modified); if you put a number that is beyond your max range, the move will be Invalid

[[messages]]
_name = "Open"     # open (a door, a chest, etc.) at a specific tile
target = "Point"   # the position *relative to you* that you want to try to open; can usually only be one square away (manhattan distance); if already opened, move will fail; if target is not openable, move will be Invalid

[[messages]]
_name = "Close"    # close (a door, a chest, etc.) at a specific tile
target = "Point"   # the position *relative to you* that you want to try to close; can usually only be one square away (manhattan distance); if already closed, move will fail; if target is not closable, move will be Invalid

-----------------
END DATA PROTOCOL
*/



const _textDec = new TextDecoder('utf-8');
const _textEnc = new TextEncoder();

export class DataAccess {
	data: DataView;
	currentOffset: number;

	constructor(buffer: ArrayBuffer|DataView) {
		this.currentOffset = 0;
		if (buffer instanceof ArrayBuffer) {
			this.data = new DataView(buffer);
		}
		else {
			this.data = buffer;
		}
	}

	isFinished(): boolean {
		return this.currentOffset >= this.data.byteLength;
	}

	getByte(): number {
		const ret = this.data.getUint8(this.currentOffset);
		this.currentOffset += 1;
		return ret;
	}

	getBool(): boolean {
		return this.getByte() > 0;
	}

	getInt16(): number {
		const ret = this.data.getInt16(this.currentOffset, true);
		this.currentOffset += 2;
		return ret;
	}

	getUint16(): number {
		const ret = this.data.getUint16(this.currentOffset, true);
		this.currentOffset += 2;
		return ret;
	}

	getInt32(): number {
		const ret = this.data.getInt32(this.currentOffset, true);
		this.currentOffset += 4;
		return ret;
	}

	getUint32(): number {
		const ret = this.data.getUint32(this.currentOffset, true);
		this.currentOffset += 4;
		return ret;
	}

	getInt64(): bigint {
		const ret = this.data.getBigInt64(this.currentOffset, true);
		this.currentOffset += 8;
		return ret;
	}

	getUint64(): bigint {
		const ret = this.data.getBigUint64(this.currentOffset, true);
		this.currentOffset += 8;
		return ret;
	}

	getFloat32(): number {
		const ret = this.data.getFloat32(this.currentOffset, true);
		this.currentOffset += 4;
		return Math.fround(ret);
	}

	getFloat64(): number {
		const ret = this.data.getFloat64(this.currentOffset, true);
		this.currentOffset += 8;
		return ret;
	}

	getString(): string {
		const len = this.getByte();
		const strBuffer = new Uint8Array(this.data.buffer, this.currentOffset, len);
		this.currentOffset += len;
		return _textDec.decode(strBuffer);
	}


	setByte(val: number) {
		this.data.setUint8(this.currentOffset, val);
		this.currentOffset += 1;
	}

	setBool(val: boolean): void {
		this.setByte(val ? 1 : 0);
	}

	setInt16(val: number): void {
		this.data.setInt16(this.currentOffset, val, true);
		this.currentOffset += 2;
	}

	setUint16(val: number): void {
		this.data.setUint16(this.currentOffset, val, true);
		this.currentOffset += 2;
	}

	setInt32(val: number): void {
		this.data.setInt32(this.currentOffset, val, true);
		this.currentOffset += 4;
	}

	setUint32(val: number): void {
		this.data.setUint32(this.currentOffset, val, true);
		this.currentOffset += 4;
	}

	setInt64(val: bigint): void {
		this.data.setBigInt64(this.currentOffset, val, true);
		this.currentOffset += 8;
	}

	setUint64(val: bigint): void {
		this.data.setBigUint64(this.currentOffset, val, true);
		this.currentOffset += 8;
	}

	setFloat32(val: number): void {
		this.data.setFloat32(this.currentOffset, val, true);
		this.currentOffset += 4;
	}

	setFloat64(val: number): void {
		this.data.setFloat64(this.currentOffset, val, true);
		this.currentOffset += 8;
	}

	setString(val: string): void {
		const strBuffer = _textEnc.encode(val);
		this.setByte(strBuffer.byteLength);
		const arr = new Uint8Array(this.data.buffer, this.data.byteOffset, this.data.byteLength);
		arr.set(strBuffer, this.currentOffset);
		this.currentOffset += strBuffer.byteLength;
	}
}

export abstract class Message {
	abstract getMessageType(): MessageType;
	abstract writeBytes(dv: DataView|DataAccess, tag: boolean): void;
	abstract getSizeInBytes(): number;

	static fromBytes(data: DataView|DataAccess|ArrayBuffer): Message | null {
		throw new Error("Cannot read abstract Message from bytes.");
	};
}

export function GetPackedSize(msgList: Message[]): number {
	let size = 0;
	for (const msg of msgList) {
		size += msg.getSizeInBytes();
	}
	size += msgList.length;
	size += 9;
	return size;
}

export function PackMessages(msgList: Message[], data: DataView|DataAccess): void {
	let da: DataAccess;
	if (data instanceof DataView) {
		da = new DataAccess(data);
	}
	else {
		da = data;
	}
	const headerBytes = _textEnc.encode("BSCI");
	const arr = new Uint8Array(da.data.buffer);
	arr.set(headerBytes, da.currentOffset);
	da.currentOffset += headerBytes.byteLength;
	da.setUint32(msgList.length);
	for (const msg of msgList) {
		msg.writeBytes(da, true);
	}
	da.setByte(0);
}

export function UnpackMessages(data: DataView|DataAccess): Message[] {
	let da: DataAccess;
	if (data instanceof DataView) {
		da = new DataAccess(data);
	}
	else {
		da = data;
	}
	const headerBuffer = new Uint8Array(da.data.buffer, da.currentOffset, 4);
	da.currentOffset += 4;
	const headerLabel = _textDec.decode(headerBuffer);
	if (headerLabel !== "BSCI") {
		throw new Error("Packed message buffer has invalid header.");
	}
	const msgCount = da.getUint32();
	if (msgCount == 0) {
		return [];
	}
	const msgList = ProcessRawBytes(da, msgCount);
	if (msgList.length == 0) {
		throw new Error("No messages in buffer.");
	}
	if (msgList.length != msgCount) {
		throw new Error("Unexpected number of messages in buffer.");
	}
	return msgList;
}

export enum MessageType {
	_ErrorType = 1,
	InitialParametersType = 2,
	PresentCircumstancesType = 3,
	WaitType = 4,
	ResignType = 5,
	MoveToType = 6,
	OpenType = 7,
	CloseType = 8,
}

export function ProcessRawBytes(data: DataView|DataAccess, max: number): Message[] {
	if (max === undefined) {
		max = -1;
	}
	let da: DataAccess;
	if (data instanceof DataView) {
		da = new DataAccess(data);
	}
	else {
		da = data;
	}
	const msgList: Message[] = [];
	if (max == 0) {
		return msgList;
	}
	while (!da.isFinished() && (max < 0 || msgList.length < max)) {
		const msgType: number = da.getByte();
		let newMsg: Message | null;
		switch (msgType) {
			case 0:
				return msgList;
			case MessageType._ErrorType:
				newMsg = _Error.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.InitialParametersType:
				newMsg = InitialParameters.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.PresentCircumstancesType:
				newMsg = PresentCircumstances.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.WaitType:
				newMsg = Wait.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.ResignType:
				newMsg = Resign.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.MoveToType:
				newMsg = MoveTo.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.OpenType:
				newMsg = Open.fromBytes(da);
				msgList.push(newMsg);
				break;
			case MessageType.CloseType:
				newMsg = Close.fromBytes(da);
				msgList.push(newMsg);
				break;
			default:
				throw new Error(`Unknown message type: ${msgType}`);
		}
	}
	return msgList;
}

export enum GameMode {
	Wander = 0,
	Attain = 1,
}

export enum MoveResult {
	Succeeded = 0,
	Failed = 1,
	Invalid = 2,
	Error = 3,
}

export enum TileType {
	Void = 0,
	Floor = 1,
	OpenDoor = 2,
	ClosedDoor = 3,
	Wall = 4,
}

export enum Direction {
	North = 0,
	Northeast = 1,
	East = 2,
	Southeast = 3,
	South = 4,
	Southwest = 5,
	West = 6,
	Northwest = 7,
}

export enum EntityType {
	Player = 0,
	Item = 1,
}

export enum ItemType {
	Stone = 0,
	Amulet = 1,
}

export class Point {
	x: number = 0;
	y: number = 0;

	static fromBytes(da: DataAccess): Point {
		const nPoint = new Point();
		nPoint.x = da.getInt16();
		nPoint.y = da.getInt16();
		return nPoint;
	}

	writeBytes(da: DataAccess): void {
		da.setInt16(this.x);
		da.setInt16(this.y);
	}
}

export class Entity {
	id: number = 0;
	entityType: EntityType = EntityType.Player;
	surroundingsIndex: number = 0;
	label: string = "";
	dataByteA: number = 0;
	dataByteB: number = 0;
	dataIntA: number = 0;
	dataIntB: number = 0;

	static fromBytes(da: DataAccess): Entity {
		const nEntity = new Entity();
		nEntity.id = da.getUint32();
		const _entityType = da.getByte();
		if (EntityType[_entityType] === undefined) {
			throw new Error(`Enum (${_entityType}) out of range for EntityType`);
		}
		nEntity.entityType = _entityType;
		nEntity.surroundingsIndex = da.getUint16();
		nEntity.label = da.getString();
		nEntity.dataByteA = da.getByte();
		nEntity.dataByteB = da.getByte();
		nEntity.dataIntA = da.getInt32();
		nEntity.dataIntB = da.getInt32();
		return nEntity;
	}

	writeBytes(da: DataAccess): void {
		da.setUint32(this.id);
		da.setByte(this.entityType);
		da.setUint16(this.surroundingsIndex);
		da.setString(this.label);
		da.setByte(this.dataByteA);
		da.setByte(this.dataByteB);
		da.setInt32(this.dataIntA);
		da.setInt32(this.dataIntB);
	}
}

export class _Error extends Message {
	description: string = "";

	getMessageType() : MessageType { return MessageType._ErrorType; }

	getSizeInBytes(): number {
		let size: number = 0;
		size += _textEnc.encode(this.description).byteLength;
		size += 1;
		return size;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): _Error {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const n_Error = new _Error();
			n_Error.description = da.getString();
			return n_Error;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read _Error from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType._ErrorType);
		}
		da.setString(this.description);
	}
}

export class InitialParameters extends Message {
	paramsVersion: number = 0;
	engineVersionMajor: number = 0;
	engineVersionMinor: number = 0;
	engineVersionPatch: number = 0;
	diagonalMovement: boolean = false;
	playerStride: number = 0;
	playerOpenReach: number = 0;
	gameMode: GameMode = GameMode.Wander;

	getMessageType() : MessageType { return MessageType.InitialParametersType; }

	getSizeInBytes(): number {
		return 12;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): InitialParameters {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nInitialParameters = new InitialParameters();
			nInitialParameters.paramsVersion = da.getUint16();
			nInitialParameters.engineVersionMajor = da.getUint16();
			nInitialParameters.engineVersionMinor = da.getUint16();
			nInitialParameters.engineVersionPatch = da.getUint16();
			nInitialParameters.diagonalMovement = da.getBool();
			nInitialParameters.playerStride = da.getByte();
			nInitialParameters.playerOpenReach = da.getByte();
			const _gameMode = da.getByte();
			if (GameMode[_gameMode] === undefined) {
				throw new Error(`Enum (${_gameMode}) out of range for GameMode`);
			}
			nInitialParameters.gameMode = _gameMode;
			return nInitialParameters;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read InitialParameters from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.InitialParametersType);
		}
		da.setUint16(this.paramsVersion);
		da.setUint16(this.engineVersionMajor);
		da.setUint16(this.engineVersionMinor);
		da.setUint16(this.engineVersionPatch);
		da.setBool(this.diagonalMovement);
		da.setByte(this.playerStride);
		da.setByte(this.playerOpenReach);
		da.setByte(this.gameMode);
	}
}

export class PresentCircumstances extends Message {
	lastTickDuration: number = 0;
	lastMoveResult: MoveResult = MoveResult.Succeeded;
	currentHitPoints: number = 0;
	surroundings: TileType[] = [];
	surroundingsRadius: number = 0;
	visibleEntities: Entity[] = [];

	getMessageType() : MessageType { return MessageType.PresentCircumstancesType; }

	getSizeInBytes(): number {
		let size: number = 0;
		size += this.surroundings.length * 1;
		for (let visibleEntities_i=0; visibleEntities_i < this.visibleEntities.length; visibleEntities_i++) {
			size += _textEnc.encode(this.visibleEntities[visibleEntities_i].label).byteLength;
			size += 18;
		}
		size += 12;
		return size;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): PresentCircumstances {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nPresentCircumstances = new PresentCircumstances();
			nPresentCircumstances.lastTickDuration = da.getUint32();
			const _lastMoveResult = da.getByte();
			if (MoveResult[_lastMoveResult] === undefined) {
				throw new Error(`Enum (${_lastMoveResult}) out of range for MoveResult`);
			}
			nPresentCircumstances.lastMoveResult = _lastMoveResult;
			nPresentCircumstances.currentHitPoints = da.getUint16();
			const surroundings_Length = da.getUint16();
			nPresentCircumstances.surroundings = new Array<TileType>(surroundings_Length);
			for (let i3: number = 0; i3 < surroundings_Length; i3++) {
				const _surroundings = da.getByte();
				if (TileType[_surroundings] === undefined) {
					throw new Error(`Enum (${_surroundings}) out of range for TileType`);
				}
				nPresentCircumstances.surroundings[i3] = _surroundings;
			}
			nPresentCircumstances.surroundingsRadius = da.getByte();
			const visibleEntities_Length = da.getUint16();
			nPresentCircumstances.visibleEntities = new Array<Entity>(visibleEntities_Length);
			for (let i3: number = 0; i3 < visibleEntities_Length; i3++) {
				nPresentCircumstances.visibleEntities[i3] = Entity.fromBytes(da);
			}
			return nPresentCircumstances;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read PresentCircumstances from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.PresentCircumstancesType);
		}
		da.setUint32(this.lastTickDuration);
		da.setByte(this.lastMoveResult);
		da.setUint16(this.currentHitPoints);
		da.setUint16(this.surroundings.length);
		for (let i = 0; i < this.surroundings.length; i++) {
			let el = this.surroundings[i];
			da.setByte(el);
		}
		da.setByte(this.surroundingsRadius);
		da.setUint16(this.visibleEntities.length);
		for (let i = 0; i < this.visibleEntities.length; i++) {
			let el = this.visibleEntities[i];
			el.writeBytes(da);
		}
	}
}

export class Wait extends Message {

	getMessageType() : MessageType { return MessageType.WaitType; }

	getSizeInBytes(): number {
		return 0;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): Wait {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nWait = new Wait();
			return nWait;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read Wait from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.WaitType);
		}
	}
}

export class Resign extends Message {

	getMessageType() : MessageType { return MessageType.ResignType; }

	getSizeInBytes(): number {
		return 0;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): Resign {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nResign = new Resign();
			return nResign;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read Resign from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.ResignType);
		}
	}
}

export class MoveTo extends Message {
	direction: Direction = Direction.North;
	distance: number = 0;

	getMessageType() : MessageType { return MessageType.MoveToType; }

	getSizeInBytes(): number {
		return 2;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): MoveTo {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nMoveTo = new MoveTo();
			const _direction = da.getByte();
			if (Direction[_direction] === undefined) {
				throw new Error(`Enum (${_direction}) out of range for Direction`);
			}
			nMoveTo.direction = _direction;
			nMoveTo.distance = da.getByte();
			return nMoveTo;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read MoveTo from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.MoveToType);
		}
		da.setByte(this.direction);
		da.setByte(this.distance);
	}
}

export class Open extends Message {
	target: Point = new Point();

	getMessageType() : MessageType { return MessageType.OpenType; }

	getSizeInBytes(): number {
		return 4;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): Open {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nOpen = new Open();
			nOpen.target = Point.fromBytes(da);
			return nOpen;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read Open from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.OpenType);
		}
		this.target.writeBytes(da);
	}
}

export class Close extends Message {
	target: Point = new Point();

	getMessageType() : MessageType { return MessageType.CloseType; }

	getSizeInBytes(): number {
		return 4;
	}

	static override fromBytes(data: DataView|DataAccess|ArrayBuffer): Close {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else if (data instanceof ArrayBuffer) {
			da = new DataAccess(new DataView(data));
		}
		else {
			da = data;
		}
		try {
			const nClose = new Close();
			nClose.target = Point.fromBytes(da);
			return nClose;
		}
		catch (err) {
			let errMsg = "[Unknown error]";
			if (err instanceof Error) {
				errMsg = `${err.name} -- ${err.message}`;
			}
			throw new Error(`Could not read Close from offset ${da.currentOffset} (${errMsg})`);
		}
	}

	writeBytes(data: DataView|DataAccess, tag: boolean): void {
		let da: DataAccess;
		if (data instanceof DataView) {
			da = new DataAccess(data);
		}
		else {
			da = data;
		}
		if (tag) {
			da.setByte(MessageType.CloseType);
		}
		this.target.writeBytes(da);
	}
}

export const MessageTypeMap = new Map<MessageType, { new(): Message }>([
	[MessageType._ErrorType, _Error],
	[MessageType.InitialParametersType, InitialParameters],
	[MessageType.PresentCircumstancesType, PresentCircumstances],
	[MessageType.WaitType, Wait],
	[MessageType.ResignType, Resign],
	[MessageType.MoveToType, MoveTo],
	[MessageType.OpenType, Open],
	[MessageType.CloseType, Close],
]);

