// This file was automatically generated by Beschi v0.2.0
// <https://github.com/sjml/beschi>
// Do not edit directly.


const _textDec = new TextDecoder('utf-8');
const _textEnc = new TextEncoder();

export class DataAccess {
    buffer: DataView;
    currentOffset: number;

    constructor(buffer: ArrayBuffer|DataView) {
        this.currentOffset = 0;
        if (buffer instanceof ArrayBuffer) {
            this.buffer = new DataView(buffer);
        }
        else {
            this.buffer = buffer;
        }
    }

    isFinished(): boolean {
        return this.currentOffset >= this.buffer.byteLength;
    }

    getByte(): number {
        const ret = this.buffer.getUint8(this.currentOffset);
        this.currentOffset += 1;
        return ret;
    }

    getBool(): boolean {
        return this.getByte() > 0;
    }

    getInt16(): number {
        const ret = this.buffer.getInt16(this.currentOffset, true);
        this.currentOffset += 2;
        return ret;
    }

    getUint16(): number {
        const ret = this.buffer.getUint16(this.currentOffset, true);
        this.currentOffset += 2;
        return ret;
    }

    getInt32(): number {
        const ret = this.buffer.getInt32(this.currentOffset, true);
        this.currentOffset += 4;
        return ret;
    }

    getUint32(): number {
        const ret = this.buffer.getUint32(this.currentOffset, true);
        this.currentOffset += 4;
        return ret;
    }

    getInt64(): bigint {
        const ret = this.buffer.getBigInt64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getUint64(): bigint {
        const ret = this.buffer.getBigUint64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getFloat32(): number {
        const ret = this.buffer.getFloat32(this.currentOffset, true);
        this.currentOffset += 4;
        return Math.fround(ret);
    }

    getFloat64(): number {
        const ret = this.buffer.getFloat64(this.currentOffset, true);
        this.currentOffset += 8;
        return ret;
    }

    getString(): string {
        const len = this.getByte();
        const strBuffer = new Uint8Array(this.buffer.buffer, this.currentOffset, len);
        this.currentOffset += len;
        return _textDec.decode(strBuffer);
    }


    setByte(val: number) {
        this.buffer.setUint8(this.currentOffset, val);
        this.currentOffset += 1;
    }

    setBool(val: boolean) {
        this.setByte(val ? 1 : 0);
    }

    setInt16(val: number) {
        this.buffer.setInt16(this.currentOffset, val, true);
        this.currentOffset += 2;
    }

    setUint16(val: number) {
        this.buffer.setUint16(this.currentOffset, val, true);
        this.currentOffset += 2;
    }

    setInt32(val: number) {
        this.buffer.setInt32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setUint32(val: number) {
        this.buffer.setUint32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setInt64(val: bigint) {
        this.buffer.setBigInt64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setUint64(val: bigint) {
        this.buffer.setBigUint64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setFloat32(val: number) {
        this.buffer.setFloat32(this.currentOffset, val, true);
        this.currentOffset += 4;
    }

    setFloat64(val: number) {
        this.buffer.setFloat64(this.currentOffset, val, true);
        this.currentOffset += 8;
    }

    setString(val: string) {
        const strBuffer = _textEnc.encode(val);
        this.setByte(strBuffer.byteLength);
        const arr = new Uint8Array(this.buffer.buffer);
        arr.set(strBuffer, this.currentOffset);
        this.currentOffset += strBuffer.byteLength;
    }
}

export enum MessageType {
  _ErrorType = 1,
  InitialParametersType = 2,
  PresentCircumstancesType = 3,
  WaitType = 4,
  ResignType = 5,
  MoveType = 6,
}

export interface Message {
  getMessageType(): MessageType;
  writeBytes(dv: DataView, tag: boolean): void;
  getSizeInBytes(): number;
}
export interface MessageStatic {
  new(): Message;
  fromBytes(dv: DataView): Message | null;
}
function staticImplements<T>() {
  return (constructor: T) => {}
}

export function ProcessRawBytes(dv: DataView): Message[] {
  const da = new DataAccess(dv);
  const msgList: Message[] = [];
  while (!da.isFinished()) {
    const msgType: number = da.getByte();
    switch (msgType) {
      case 0:
        return msgList;
      case MessageType._ErrorType:
        msgList.push(_Error.fromBytes(da));
        break;
      case MessageType.InitialParametersType:
        msgList.push(InitialParameters.fromBytes(da));
        break;
      case MessageType.PresentCircumstancesType:
        msgList.push(PresentCircumstances.fromBytes(da));
        break;
      case MessageType.WaitType:
        msgList.push(Wait.fromBytes(da));
        break;
      case MessageType.ResignType:
        msgList.push(Resign.fromBytes(da));
        break;
      case MessageType.MoveType:
        msgList.push(Move.fromBytes(da));
        break;
      default:
        throw new Error(`Unknown message type: ${msgType}`);
    }
  }
  return msgList;
}

@staticImplements<MessageStatic>()
export class _Error implements Message {
  description: string = "";

  getMessageType() : MessageType { return MessageType._ErrorType; }

  getSizeInBytes(): number {
    let size: number = 0;
    size += _textEnc.encode(this.description).byteLength;
    size += 1;
    return size;
  }

  static fromBytes(data: DataView|DataAccess): _Error {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const n_Error = new _Error();
      n_Error.description = da.getString();
      return n_Error;
    }
    catch (err) {
      throw new Error(`Could not read _Error from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType._ErrorType);
    }
    da.setString(this.description);
  }

}

@staticImplements<MessageStatic>()
export class InitialParameters implements Message {
  paramsVersion: number = 0;
  engineVersionMajor: number = 0;
  engineVersionMinor: number = 0;
  engineVersionPatch: number = 0;

  getMessageType() : MessageType { return MessageType.InitialParametersType; }

  getSizeInBytes(): number {
    return 8;
  }

  static fromBytes(data: DataView|DataAccess): InitialParameters {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nInitialParameters = new InitialParameters();
      nInitialParameters.paramsVersion = da.getUint16();
      nInitialParameters.engineVersionMajor = da.getUint16();
      nInitialParameters.engineVersionMinor = da.getUint16();
      nInitialParameters.engineVersionPatch = da.getUint16();
      return nInitialParameters;
    }
    catch (err) {
      throw new Error(`Could not read InitialParameters from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.InitialParametersType);
    }
    da.setUint16(this.paramsVersion);
    da.setUint16(this.engineVersionMajor);
    da.setUint16(this.engineVersionMinor);
    da.setUint16(this.engineVersionPatch);
  }

}

@staticImplements<MessageStatic>()
export class PresentCircumstances implements Message {
  lastTickDuration: number = 0;
  lastMoveSucceeded: boolean = false;
  currentHitPoints: number = 0;
  currentStatus: number = 0;
  surroundings: number[] = [];
  surroundingsRadius: number = 0;

  getMessageType() : MessageType { return MessageType.PresentCircumstancesType; }

  getSizeInBytes(): number {
    let size: number = 0;
    size += this.surroundings.length * 2;
    size += 11;
    return size;
  }

  static fromBytes(data: DataView|DataAccess): PresentCircumstances {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nPresentCircumstances = new PresentCircumstances();
      nPresentCircumstances.lastTickDuration = da.getUint32();
      nPresentCircumstances.lastMoveSucceeded = da.getBool();
      nPresentCircumstances.currentHitPoints = da.getUint16();
      nPresentCircumstances.currentStatus = da.getByte();
      const surroundings_Length = da.getUint16();
      nPresentCircumstances.surroundings = Array<number>(surroundings_Length);
      for (let i3 = 0; i3 < surroundings_Length; i3++) {
        nPresentCircumstances.surroundings[i3] = da.getUint16();
      }
      nPresentCircumstances.surroundingsRadius = da.getByte();
      return nPresentCircumstances;
    }
    catch (err) {
      throw new Error(`Could not read PresentCircumstances from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.PresentCircumstancesType);
    }
    da.setUint32(this.lastTickDuration);
    da.setBool(this.lastMoveSucceeded);
    da.setUint16(this.currentHitPoints);
    da.setByte(this.currentStatus);
    da.setUint16(this.surroundings.length);
    for (let i = 0; i < this.surroundings.length; i++) {
      let el = this.surroundings[i];
      da.setUint16(el);
    }
    da.setByte(this.surroundingsRadius);
  }

}

@staticImplements<MessageStatic>()
export class Wait implements Message {

  getMessageType() : MessageType { return MessageType.WaitType; }

  getSizeInBytes(): number {
    return 0;
  }

  static fromBytes(data: DataView|DataAccess): Wait {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nWait = new Wait();
      return nWait;
    }
    catch (err) {
      throw new Error(`Could not read Wait from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.WaitType);
    }
  }

}

@staticImplements<MessageStatic>()
export class Resign implements Message {

  getMessageType() : MessageType { return MessageType.ResignType; }

  getSizeInBytes(): number {
    return 0;
  }

  static fromBytes(data: DataView|DataAccess): Resign {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nResign = new Resign();
      return nResign;
    }
    catch (err) {
      throw new Error(`Could not read Resign from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.ResignType);
    }
  }

}

@staticImplements<MessageStatic>()
export class Move implements Message {
  direction: number = 0;
  distance: number = 0;

  getMessageType() : MessageType { return MessageType.MoveType; }

  getSizeInBytes(): number {
    return 2;
  }

  static fromBytes(data: DataView|DataAccess): Move {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    try {
      const nMove = new Move();
      nMove.direction = da.getByte();
      nMove.distance = da.getByte();
      return nMove;
    }
    catch (err) {
      throw new Error(`Could not read Move from offset ${da.currentOffset} (${err.name})`);
    }
  }

  writeBytes(data: DataView|DataAccess, tag: boolean): void {
    let da: DataAccess;
    if (data instanceof DataView) {
      da = new DataAccess(data);
    }
    else {
      da = data;
    }
    if (tag) {
      da.setByte(MessageType.MoveType);
    }
    da.setByte(this.direction);
    da.setByte(this.distance);
  }

}

export const MessageTypeMap = new Map<MessageType, { new(): Message }>([
  [MessageType._ErrorType, _Error],
  [MessageType.InitialParametersType, InitialParameters],
  [MessageType.PresentCircumstancesType, PresentCircumstances],
  [MessageType.WaitType, Wait],
  [MessageType.ResignType, Resign],
  [MessageType.MoveType, Move],
]);

