name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Devbox + Dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true
      - name: Build Distribution Site
        run: |
          devbox run build
      - name: Upload Distribution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasmbots-dist
          path: frontend/build
      - name: Build GitHub Pages Site
        run: |
          cd frontend
          devbox run --env WASMBOTS_BASE="/wasmbots" npm run build
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
